/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false -c /tmp/test-wrangler.jsonc` (hash: b862cd2d59680e5112ccf83383c3cc8d)
declare namespace Cloudflare {
	interface Env {
		USER_NOTIFICATION: KVNamespace;
		BLOG_WORKFLOW_STATE: KVNamespace;
		GEMINI_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
