/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 53f7a89966ba5a8b5f1087d24d85c45a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		USER_NOTIFICATION: KVNamespace;
		BLOG_WORKFLOW_STATE: KVNamespace;
		GEMINI_API_KEY: string;
		API_KEY: string;
		ADMIN_API_KEY: string;
		CF_ACCESS_AUD: string;
		ALERT_WEBHOOK_URL: string;
		WP_SITE_URL: string;
		WP_USER: string;
		WP_APP_PASSWORD: string;
		WHATSAPP_VERIFY_TOKEN?: string;
		WHATSAPP_APP_SECRET?: string;
		WHATSAPP_ACCESS_TOKEN?: string;
		WHATSAPP_PHONE_NUMBER_ID?: string;
		WHATSAPP_ADMIN_NUMBER?: string;
	}
}
interface Env extends Cloudflare.Env {}
