// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2905fd8e181cd2f4083a615fa51f1913)
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		USER_NOTIFICATION: KVNamespace;
		/** KV namespace for persisting blog workflow state, logs, and errors. */
		BLOG_WORKFLOW_STATE: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
